#ifndef RADIOINTERFACE_H
#define RADIOINTERFACE_H

#include <Arduino.h>

#define MESSAGE_SEND 0
#define MESSAGE_SET_MODE 1
#define MESSAGE_SET_FREQUENCY 2
#define MESSAGE_SET_DATARATE 3
#define MESSAGE_SET_INTERVAL 4
#define MESSAGE_SET_LENGTH 5
#define MESSAGE_SET_CONTINUOUS 6
#define MESSAGE_QUICKSAVE 0xF5
#define MESSAGE_QUICKLOAD 0xF9
#define MESSAGE_QUICKACK 0xFA
#define MESSAGE_SEND_CONFIG 7
#define MESSAGE_ARM 8
#define MESSAGE_DISARM 9

#endif
